server:
  port: 80
#  servlet:
#    session:
##      cookie:
##        http-only: true
#       timeout: 18000000


spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://localhost:3306/gzp
          username: root
          password: root
          #配置初始化大小/最小 /最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 20000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 20000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      joda-date-time-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    redis:
      host: localhost
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms

    devtools:
        restart:
          enabled: true  #设置开启热部署
#    jpa:
#      show-sql: true

    http:
       multipart:
         maxFileSize: 10Mb
         maxRequestSize: 100Mb
token:
  expire:
    seconds: 14400
  jwtSecret: (TANG:)_$^11244^%$_(JIAN:)_@@++--(BO:)_++++_.sds_(A:)

file:
  imgPath: E:/home/image/
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.tang.dao.mapper
#
##pagehelper
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#    returnPageInfo: check

#logging:
#    config: classpath:logback-admin.xml
#  log:
#    level:
#      root: info
#      my: debug
#    file: logs/admin-server.log
#    maxsize: 30MB